services:
  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.API
    ports:
      - "8085:8085"
    environment:
      # Environment
      ENV: prod
      
      # Service Configuration
      SERVICE_ADDRESS: /identity-api/api
      SERVICE_PORT: :8085
      # Redis Configuration
      REDIS_HOST: redis_container
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
      # JWT Configuration
      ACCESS_TOKEN_TTL: 15
      REFRESH_TOKEN_TTL: 30
      SECRET_KEY: your_secret_key_here
      # PostgreSQL Configuration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Identity_db
      POSTGRES_HOST: Identity_postgres
      POSTGRES_PORT: 5432
      RUN_POSTGRES_MIGRATION: "true"
      
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge