services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - redis_data:/data
      - ../Infrastructure/databases/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - docker-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_db
      POSTGRES_MULTIPLE_DATABASES: "blog_db,rental_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
      - ./postgres/create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh
    networks:
      - docker-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8086:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula
    depends_on:
      - postgres
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
