version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge