FROM golang:1.23-alpine AS builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod ./

RUN go mod tidy

COPY . .

RUN go build -o /go-api ./cmd/service

RUN ls -la /app

FROM alpine:latest

COPY --from=builder /go-api /go-api

EXPOSE 8088

CMD ["/go-api"]