definitions:
  contract.DeleteFileRequest:
    properties:
      file_id:
        type: string
      owner_id:
        type: string
    type: object
  contract.DeleteFileResponse200:
    properties:
      message:
        example: File deleted successfully.
        type: string
      title:
        example: StatusOK
        type: string
    type: object
  contract.DeleteFileResponse400:
    properties:
      message:
        example: Invalid delete file request.
        type: string
      title:
        example: Bad Request
        type: string
    type: object
  contract.DeleteFileResponse404:
    properties:
      message:
        example: The requested file was not found.
        type: string
      title:
        example: Not Found
        type: string
    type: object
  contract.DeleteFileResponse500:
    properties:
      message:
        example: An unexpected error occurred.
        type: string
      title:
        example: Internal Server Error
        type: string
    type: object
  contract.GetFileResponse400:
    properties:
      message:
        example: Invalid file request.
        type: string
      title:
        example: Bad Request
        type: string
    type: object
  contract.GetFileResponse404:
    properties:
      message:
        example: The requested file was not found.
        type: string
      title:
        example: Not Found
        type: string
    type: object
  contract.GetFileResponse500:
    properties:
      message:
        example: An unexpected error occurred.
        type: string
      title:
        example: Internal Server Error
        type: string
    type: object
  contract.SaveFileResponse201:
    properties:
      id:
        type: string
      message:
        example: File saved successfully.
        type: string
      title:
        example: StatusCreated
        type: string
    type: object
  contract.SaveFileResponse400:
    properties:
      id:
        type: string
      message:
        example: Invalid save file request.
        type: string
      title:
        example: Bad Request
        type: string
    type: object
  contract.SaveFileResponse500:
    properties:
      id:
        type: string
      message:
        example: An unexpected error occurred.
        type: string
      title:
        example: Internal Server Error
        type: string
    type: object
info:
  contact: {}
paths:
  /file-storage/api/files:
    post:
      consumes:
      - multipart/form-data
      description: Uploads and saves a file in the storage system, including metadata
        and content.
      parameters:
      - description: Owner ID associated with the file
        in: formData
        name: owner_id
        required: true
        type: string
      - description: Binary file content (JPEG, PNG, etc.) to be saved
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: File saved successfully with unique ID and details
          schema:
            $ref: '#/definitions/contract.SaveFileResponse201'
        "400":
          description: Invalid request format or missing parameters
          schema:
            $ref: '#/definitions/contract.SaveFileResponse400'
        "500":
          description: Server encountered an error during file save operation
          schema:
            $ref: '#/definitions/contract.SaveFileResponse500'
      summary: Save a new file
      tags:
      - files
  /file-storage/api/files/delete:
    delete:
      consumes:
      - application/json
      description: Deletes a file from storage by its unique ID. The file ID should
        be a valid identifier for an existing file.
      parameters:
      - description: Delete file request object
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/contract.DeleteFileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: File deletion was successful
          schema:
            $ref: '#/definitions/contract.DeleteFileResponse200'
        "400":
          description: Invalid request format or parameters
          schema:
            $ref: '#/definitions/contract.DeleteFileResponse400'
        "404":
          description: File not found with the given ID
          schema:
            $ref: '#/definitions/contract.DeleteFileResponse404'
        "500":
          description: Server encountered an error during file deletion
          schema:
            $ref: '#/definitions/contract.DeleteFileResponse500'
      summary: Delete a file
      tags:
      - files
  /file-storage/api/files/get:
    get:
      consumes:
      - application/json
      description: Retrieves a file from storage by its unique identifier. The ID
        should refer to a valid, stored file, and the file is returned in its original
        format (e.g., JPEG, PNG).
      parameters:
      - description: Unique File ID for retrieval
        in: query
        name: file_id
        required: true
        type: string
      - description: Owner ID associated with the file
        in: query
        name: owner_id
        required: true
        type: string
      - description: File binary content or file to download
        in: query
        name: download
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: Successful retrieval of file in binary format or file to download
            in attachment
          schema:
            type: file
        "400":
          description: Request contains invalid format or parameters
          schema:
            $ref: '#/definitions/contract.GetFileResponse400'
        "404":
          description: File not found with the given ID
          schema:
            $ref: '#/definitions/contract.GetFileResponse404'
        "500":
          description: Server encountered an error during file retrieval
          schema:
            $ref: '#/definitions/contract.GetFileResponse500'
      summary: Get a file
      tags:
      - files
swagger: "2.0"
