services:
  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.API
    ports:
      - "8080:8080"
    environment:
      NATS_URL: nats://nats:4222
      STREAM_NAME: file_stream
      STREAM_SUBJECTS: events.*
      MAILHOG_HOST: "mailhog"
      MAILHOG_PORT: "1025"
      ENV: prod
    networks:
      - file-network

networks:
  file-network:
    driver: bridge