// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalModule.Infrastructure.DataBase.Context;

#nullable disable

namespace RentalModule.Infrastructure.DataBase.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    [Migration("20240614104445_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentalModule.Infrastructure.DataBase.Entities.CarOfferEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CarDeliverylocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CarReturnLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DriveDetails")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EngineDetails")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FeaturedImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GearboxDetails")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Horsepower")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UrlHandle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.Property<int>("YearOfProduction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarOffers");
                });

            modelBuilder.Entity("RentalModule.Infrastructure.DataBase.Entities.CarOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NumOfDrivers")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CarOrders");
                });

            modelBuilder.Entity("RentalModule.Infrastructure.DataBase.Entities.CarTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CarOfferId");

                    b.ToTable("CarTags");
                });

            modelBuilder.Entity("RentalModule.Infrastructure.DataBase.Entities.CarTariffEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("FullWeekendPrice")
                        .HasColumnType("float");

                    b.Property<double>("OneMonthPrice")
                        .HasColumnType("float");

                    b.Property<double>("OneNormalDayPrice")
                        .HasColumnType("float");

                    b.Property<double>("OneWeekPrice")
                        .HasColumnType("float");

                    b.Property<double>("OneWeekendDayPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CarOfferId")
                        .IsUnique();

                    b.ToTable("CarTariff");
                });

            modelBuilder.Entity("RentalModule.Infrastructure.DataBase.Entities.ImageUrlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CarOfferId");

                    b.ToTable("ImageUrls");
                });

            modelBuilder.Entity("RentalModule.Infrastructure.DataBase.Entities.TimePeriodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarOfferId");

                    b.ToTable("TimePeriodEntity");
                });

            modelBuilder.Entity("RentalModule.Infrastructure.DataBase.Entities.CarTagEntity", b =>
                {
                    b.HasOne("RentalModule.Infrastructure.DataBase.Entities.CarOfferEntity", null)
                        .WithMany("Tags")
                        .HasForeignKey("CarOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentalModule.Infrastructure.DataBase.Entities.CarTariffEntity", b =>
                {
                    b.HasOne("RentalModule.Infrastructure.DataBase.Entities.CarOfferEntity", null)
                        .WithOne("Tarrif")
                        .HasForeignKey("RentalModule.Infrastructure.DataBase.Entities.CarTariffEntity", "CarOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentalModule.Infrastructure.DataBase.Entities.ImageUrlEntity", b =>
                {
                    b.HasOne("RentalModule.Infrastructure.DataBase.Entities.CarOfferEntity", null)
                        .WithMany("ImageUrls")
                        .HasForeignKey("CarOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentalModule.Infrastructure.DataBase.Entities.TimePeriodEntity", b =>
                {
                    b.HasOne("RentalModule.Infrastructure.DataBase.Entities.CarOfferEntity", null)
                        .WithMany("UnavailableDates")
                        .HasForeignKey("CarOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentalModule.Infrastructure.DataBase.Entities.CarOfferEntity", b =>
                {
                    b.Navigation("ImageUrls");

                    b.Navigation("Tags");

                    b.Navigation("Tarrif")
                        .IsRequired();

                    b.Navigation("UnavailableDates");
                });
#pragma warning restore 612, 618
        }
    }
}
