// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/emails": {
            "get": {
                "description": "Retrieves a list of all emails.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "emails"
                ],
                "summary": "Get all emails",
                "responses": {
                    "200": {
                        "description": "List of emails retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/contract.GetEmailsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/contract.GetEmailsResponse"
                        }
                    },
                    "500": {
                        "description": "Server error during emails retrieval",
                        "schema": {
                            "$ref": "#/definitions/contract.GetEmailsResponse"
                        }
                    }
                }
            }
        },
        "/emails/{id}": {
            "get": {
                "description": "Retrieves an email based on its unique ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "emails"
                ],
                "summary": "Get email by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique Email ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email details retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/contract.GetEmailResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/contract.GetEmailResponse"
                        }
                    },
                    "404": {
                        "description": "Email not found",
                        "schema": {
                            "$ref": "#/definitions/contract.GetEmailResponse"
                        }
                    },
                    "500": {
                        "description": "Server error during email retrieval",
                        "schema": {
                            "$ref": "#/definitions/contract.GetEmailResponse"
                        }
                    }
                }
            }
        },
        "/send-email": {
            "post": {
                "description": "Sends an email using the provided data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "emails"
                ],
                "summary": "Send an email",
                "parameters": [
                    {
                        "description": "Email data",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.SendEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email sent successfully",
                        "schema": {
                            "$ref": "#/definitions/contract.SendEmailResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or data",
                        "schema": {
                            "$ref": "#/definitions/contract.SendEmailResponse"
                        }
                    },
                    "500": {
                        "description": "Server error during email sending",
                        "schema": {
                            "$ref": "#/definitions/contract.SendEmailResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "contract.GetEmailResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "$ref": "#/definitions/models.Email"
                },
                "message": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "contract.GetEmailsResponse": {
            "type": "object",
            "properties": {
                "emails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Email"
                    }
                },
                "message": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "contract.SendEmailRequest": {
            "type": "object",
            "required": [
                "body",
                "from",
                "subject",
                "to"
            ],
            "properties": {
                "body": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "contract.SendEmailResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.Email": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
