definitions:
  contract.GetEmailResponse:
    properties:
      email:
        $ref: '#/definitions/models.Email'
      message:
        type: string
      title:
        type: string
    type: object
  contract.GetEmailsResponse:
    properties:
      emails:
        items:
          $ref: '#/definitions/models.Email'
        type: array
      message:
        type: string
      title:
        type: string
    type: object
  contract.SendEmailRequest:
    properties:
      body:
        type: string
      from:
        type: string
      subject:
        type: string
      to:
        type: string
    required:
    - body
    - from
    - subject
    - to
    type: object
  contract.SendEmailResponse:
    properties:
      message:
        type: string
      title:
        type: string
    type: object
  models.Email:
    properties:
      body:
        type: string
      from:
        type: string
      id:
        type: string
      subject:
        type: string
      to:
        type: string
    type: object
info:
  contact: {}
paths:
  /emails:
    get:
      consumes:
      - application/json
      description: Retrieves a list of all emails.
      produces:
      - application/json
      responses:
        "200":
          description: List of emails retrieved successfully
          schema:
            $ref: '#/definitions/contract.GetEmailsResponse'
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/contract.GetEmailsResponse'
        "500":
          description: Server error during emails retrieval
          schema:
            $ref: '#/definitions/contract.GetEmailsResponse'
      summary: Get all emails
      tags:
      - emails
  /emails/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves an email based on its unique ID.
      parameters:
      - description: Unique Email ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Email details retrieved successfully
          schema:
            $ref: '#/definitions/contract.GetEmailResponse'
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/contract.GetEmailResponse'
        "404":
          description: Email not found
          schema:
            $ref: '#/definitions/contract.GetEmailResponse'
        "500":
          description: Server error during email retrieval
          schema:
            $ref: '#/definitions/contract.GetEmailResponse'
      summary: Get email by ID
      tags:
      - emails
  /send-email:
    post:
      consumes:
      - application/json
      description: Sends an email using the provided data.
      parameters:
      - description: Email data
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/contract.SendEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email sent successfully
          schema:
            $ref: '#/definitions/contract.SendEmailResponse'
        "400":
          description: Invalid request format or data
          schema:
            $ref: '#/definitions/contract.SendEmailResponse'
        "500":
          description: Server error during email sending
          schema:
            $ref: '#/definitions/contract.SendEmailResponse'
      summary: Send an email
      tags:
      - emails
swagger: "2.0"
