version: '3.8'

services:
  mongo:
    image: mongo:5.0
    networks:
      - file-network
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.currentOp()'"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongo-express:
    image: mongo-express:latest
    networks:
      - file-network
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password

  nats:
    image: nats:2.9.6-alpine
    networks:
      - file-network
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -js

volumes:
  mongo_data:

networks:
  file-network:
    driver: bridge
