FROM golang:1.20-alpine AS builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod ./

RUN go mod tidy

COPY . .

RUN go build -o /go-api cmd/service/main.go

RUN ls -la /app

FROM alpine:latest

COPY --from=builder /go-api /go-api

EXPOSE 8080

CMD ["/go-api"]