services:
  api:
    build:
      context: .
      dockerfile: ../docker/Dockerfile.API
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - nats
    environment:
      MONGO_URI: mongodb://mongo:27017/filedb
      NATS_URL: nats://nats:4222
    networks:
      - my-network

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network
  nats:
    image: nats:2.9.6-alpine
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -js
    networks:
        - my-network
volumes:
  mongo_data:

networks:
  my-network:
    driver: bridge