// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/identity-api/api/login": {
            "post": {
                "description": "Authenticates a user and returns JWT tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/contract.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/contract.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/contract.LoginResponse"
                        }
                    }
                }
            }
        },
        "/identity-api/api/register": {
            "post": {
                "description": "Registers a new user with the provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.RegisterUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User registered successfully",
                        "schema": {
                            "$ref": "#/definitions/contract.RegisterUserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/contract.RegisterUserResponse"
                        }
                    },
                    "500": {
                        "description": "Server error during registration",
                        "schema": {
                            "$ref": "#/definitions/contract.RegisterUserResponse"
                        }
                    }
                }
            }
        },
        "/identity-api/api/token/refresh": {
            "post": {
                "description": "Refreshes the JWT token using a refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "refresh",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token refreshed successfully",
                        "schema": {
                            "$ref": "#/definitions/contract.RefreshTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/contract.RefreshTokenResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid refresh token",
                        "schema": {
                            "$ref": "#/definitions/contract.RefreshTokenResponse"
                        }
                    }
                }
            }
        },
        "/identity-api/api/token/validate": {
            "get": {
                "description": "Validates the provided JWT token and returns user roles.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Validate token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token is valid",
                        "schema": {
                            "$ref": "#/definitions/contract.ValidateTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/contract.ValidateTokenResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/contract.ValidateTokenResponse"
                        }
                    },
                    "500": {
                        "description": "Server error during validation",
                        "schema": {
                            "$ref": "#/definitions/contract.ValidateTokenResponse"
                        }
                    }
                }
            }
        },
        "/identity-api/api/user": {
            "put": {
                "description": "Modifies user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Modify user",
                "parameters": [
                    {
                        "description": "User modification details",
                        "name": "modify",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.ModifyUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User modified successfully",
                        "schema": {
                            "$ref": "#/definitions/contract.ModifyUserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/contract.ModifyUserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/contract.ModifyUserResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a user from the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "description": "User deletion details",
                        "name": "delete",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.DeleteUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/contract.DeleteUserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/contract.DeleteUserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/contract.DeleteUserResponse"
                        }
                    }
                }
            }
        },
        "/identity-api/api/user/id": {
            "get": {
                "description": "Retrieves user ID based on the provided token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User ID retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/contract.GetUserIDResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/contract.GetUserIDResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/contract.GetUserIDResponse"
                        }
                    },
                    "500": {
                        "description": "Server error during retrieval",
                        "schema": {
                            "$ref": "#/definitions/contract.GetUserIDResponse"
                        }
                    }
                }
            }
        },
        "/identity-api/api/user/info": {
            "get": {
                "description": "Retrieves user information based on the provided token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User info retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/contract.GetUserInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/contract.GetUserInfoResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/contract.GetUserInfoResponse"
                        }
                    },
                    "500": {
                        "description": "Server error during retrieval",
                        "schema": {
                            "$ref": "#/definitions/contract.GetUserInfoResponse"
                        }
                    }
                }
            }
        },
        "/identity-api/api/users": {
            "get": {
                "description": "Retrieves a list of all users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get all users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Users retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/contract.GetAllUsersResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/contract.GetAllUsersResponse"
                        }
                    },
                    "500": {
                        "description": "Server error during retrieval",
                        "schema": {
                            "$ref": "#/definitions/contract.GetAllUsersResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "constants.StatusCode": {
            "type": "integer",
            "enum": [
                200,
                201,
                400,
                404,
                500,
                409
            ],
            "x-enum-varnames": [
                "StatusOK",
                "StatusCreated",
                "StatusBadRequest",
                "StatusNotFound",
                "StatusInternalServerError",
                "StatusConflict"
            ]
        },
        "contract.DeleteUserRequest": {
            "type": "object",
            "required": [
                "id",
                "token"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "12345"
                },
                "token": {
                    "type": "string",
                    "example": "jwt.token.here"
                }
            }
        },
        "contract.DeleteUserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "$ref": "#/definitions/constants.StatusCode"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "contract.GetAllUsersResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "$ref": "#/definitions/constants.StatusCode"
                },
                "success": {
                    "type": "boolean"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                }
            }
        },
        "contract.GetUserIDResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[user",
                        " admin]"
                    ]
                },
                "status_code": {
                    "$ref": "#/definitions/constants.StatusCode"
                },
                "success": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string",
                    "example": "12345"
                }
            }
        },
        "contract.GetUserInfoResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "123 Main St"
                },
                "city": {
                    "type": "string",
                    "example": "New York"
                },
                "email_address": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "12345"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "John"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+1234567890"
                },
                "postal_code": {
                    "type": "string",
                    "example": "12345"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[user",
                        " admin]"
                    ]
                },
                "status_code": {
                    "$ref": "#/definitions/constants.StatusCode"
                },
                "success": {
                    "type": "boolean"
                },
                "surname": {
                    "type": "string",
                    "example": "Doe"
                }
            }
        },
        "contract.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "password123"
                }
            }
        },
        "contract.LoginResponse": {
            "type": "object",
            "required": [
                "refresh_token",
                "token"
            ],
            "properties": {
                "message": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "jwt.refresh.token.here"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[user",
                        " admin]"
                    ]
                },
                "status_code": {
                    "$ref": "#/definitions/constants.StatusCode"
                },
                "success": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string",
                    "example": "jwt.token.here"
                }
            }
        },
        "contract.ModifyUserRequest": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "123 Main St"
                },
                "city": {
                    "type": "string",
                    "example": "New York"
                },
                "email_address": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+1234567890"
                },
                "postal_code": {
                    "type": "string",
                    "example": "12345"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[user",
                        " admin]"
                    ]
                },
                "surname": {
                    "type": "string",
                    "example": "Doe"
                },
                "token": {
                    "type": "string",
                    "example": "jwt.token.here"
                },
                "user_id": {
                    "type": "string",
                    "example": "1234567890"
                }
            }
        },
        "contract.ModifyUserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "$ref": "#/definitions/constants.StatusCode"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "contract.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "jwt.refresh.token.here"
                }
            }
        },
        "contract.RefreshTokenResponse": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "$ref": "#/definitions/constants.StatusCode"
                },
                "success": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string",
                    "example": "jwt.token.here"
                }
            }
        },
        "contract.RegisterUserRequest": {
            "type": "object",
            "required": [
                "address",
                "city",
                "email_address",
                "name",
                "password",
                "phone_number",
                "postal_code",
                "surname"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "123 Main St"
                },
                "city": {
                    "type": "string",
                    "example": "New York"
                },
                "email_address": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "password123"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+1234567890"
                },
                "postal_code": {
                    "type": "string",
                    "example": "12345"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "user",
                        "admin",
                        "superadmin"
                    ],
                    "example": "user"
                },
                "surname": {
                    "type": "string",
                    "example": "Doe"
                }
            }
        },
        "contract.RegisterUserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "$ref": "#/definitions/constants.StatusCode"
                },
                "success": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string",
                    "example": "12345"
                }
            }
        },
        "contract.ValidateTokenResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[user",
                        " admin]"
                    ]
                },
                "status_code": {
                    "$ref": "#/definitions/constants.StatusCode"
                },
                "success": {
                    "type": "boolean"
                },
                "valid": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
