definitions:
  contract.GetEmailResponse200:
    properties:
      email:
        $ref: '#/definitions/models.Email'
      message:
        example: Email retrieved successfully.
        type: string
      success:
        example: true
        type: boolean
    type: object
  contract.GetEmailResponse400:
    properties:
      email:
        type: object
      message:
        example: Invalid email request.
        type: string
      success:
        example: false
        type: boolean
    type: object
  contract.GetEmailResponse404:
    properties:
      email:
        type: object
      message:
        example: The requested email was not found.
        type: string
      success:
        example: false
        type: boolean
    type: object
  contract.GetEmailResponse500:
    properties:
      email:
        type: object
      message:
        example: An unexpected error occurred.
        type: string
      success:
        example: false
        type: boolean
    type: object
  contract.GetEmailsResponse200:
    properties:
      emails:
        items:
          $ref: '#/definitions/models.Email'
        type: array
      message:
        example: Emails retrieved successfully.
        type: string
      success:
        example: true
        type: boolean
    type: object
  contract.GetEmailsResponse400:
    properties:
      emails:
        items:
          type: object
        type: array
      message:
        example: Invalid request for emails.
        type: string
      success:
        example: false
        type: boolean
    type: object
  contract.GetEmailsResponse500:
    properties:
      emails:
        items:
          type: object
        type: array
      message:
        example: An unexpected error occurred.
        type: string
      success:
        example: false
        type: boolean
    type: object
  contract.SendEmailRequest:
    properties:
      body:
        example: This is the body of the email.
        maxLength: 1000
        minLength: 5
        type: string
      from:
        example: test@test.com
        type: string
      subject:
        example: Hello
        maxLength: 100
        minLength: 5
        type: string
      to:
        example: recipient@example.com
        type: string
    required:
    - body
    - from
    - subject
    - to
    type: object
  contract.SendEmailResponse200:
    properties:
      message:
        example: Email sent successfully.
        type: string
      success:
        example: true
        type: boolean
    type: object
  contract.SendEmailResponse400:
    properties:
      message:
        example: Invalid request for sending email.
        type: string
      success:
        example: false
        type: boolean
    type: object
  contract.SendEmailResponse500:
    properties:
      message:
        example: An unexpected error occurred while sending email.
        type: string
      success:
        example: false
        type: boolean
    type: object
  models.Email:
    properties:
      body:
        example: This is the body of the email.
        type: string
      from:
        example: example@example.com
        type: string
      id:
        example: "12345"
        type: string
      subject:
        example: Hello World
        type: string
      to:
        example: recipient@example.com
        type: string
    type: object
info:
  contact: {}
paths:
  /identity-api/api/emails:
    get:
      consumes:
      - application/json
      description: Retrieves a list of all emails.
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of emails per page
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of emails retrieved successfully
          schema:
            $ref: '#/definitions/contract.GetEmailsResponse200'
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/contract.GetEmailsResponse400'
        "500":
          description: Server error during emails retrieval
          schema:
            $ref: '#/definitions/contract.GetEmailsResponse500'
      summary: Get all emails
      tags:
      - emails
  /identity-api/api/emails/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves an email based on its unique ID.
      parameters:
      - description: Unique Email ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Email details retrieved successfully
          schema:
            $ref: '#/definitions/contract.GetEmailResponse200'
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/contract.GetEmailResponse400'
        "404":
          description: Email not found
          schema:
            $ref: '#/definitions/contract.GetEmailResponse404'
        "500":
          description: Server error during email retrieval
          schema:
            $ref: '#/definitions/contract.GetEmailResponse500'
      summary: Get email by ID
      tags:
      - emails
  /identity-api/api/send-email:
    post:
      consumes:
      - application/json
      description: Sends an email using the provided data.
      parameters:
      - description: Email data
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/contract.SendEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email sent successfully
          schema:
            $ref: '#/definitions/contract.SendEmailResponse200'
        "400":
          description: Invalid request format or data
          schema:
            $ref: '#/definitions/contract.SendEmailResponse400'
        "500":
          description: Server error during email sending
          schema:
            $ref: '#/definitions/contract.SendEmailResponse500'
      summary: Send an email
      tags:
      - emails
swagger: "2.0"
