services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docker-network

  adminer:
    image: adminer
    container_name: Identity_adminer
    ports:
      - "8086:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula  # Optional: nice dark theme
    depends_on:
      - postgres
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
