services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - redis_data:/data
      - ../Infrastructure/databases/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - docker-network

  postgres:
    image: postgres:latest
    container_name: Identity_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Identity_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docker-network

  adminer:
    image: adminer
    container_name: Identity_adminer
    ports:
      - "8086:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula  # Optional: nice dark theme
    depends_on:
      - postgres
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
