services:
  blog-api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.API
    ports:
      - "8087:8087"
    environment:
      # Environment
      ENV: prod
      # Service Configuration
      SERVICE_ADDRESS: /blog-api/api
      SERVICE_PORT: :8087
      # PostgreSQL Configuration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      RUN_POSTGRES_MIGRATION: "true"
      IDENTITY_API_URL: http://identity-api:8085
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge