version: '3.8'

services:
  api-gateway:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - SERVICE_PORT=8000
      - FILE_SERVICE_URL=http://file-service:8080
      - EMAIL_SERVICE_URL=http://email-service:8080
      - REQUEST_SENT_LIMIT=100
      - REQUEST_SENT_TIME_WINDOW=60
      - REQUEST_SIZE_LIMIT=10
      - ENV=TEST
    depends_on:
      - file-service
      - email-service
    networks:
      - api-gateway-network

  file-service:
    image: file-service:latest
    ports:
      - "8080:8080"
    networks:
      - api-gateway-network

  email-service:
    image: email-service:latest
    ports:
      - "8081:8080"
    networks:
      - api-gateway-network

networks:
  api-gateway-network:
    driver: bridge
