// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package p

import (
	"file-storage/Application/commands"
	"file-storage/Application/queries"
	"file-storage/infrastructure"
)

// Injectors from wire.go:

func InitializeSaveFileCommand() *commands.SaveFileCommand {
	fileRepository := infrastructure.ProvideFileRepository()
	eventPublisher := infrastructure.ProvideEventPublisher()
	saveFileCommand := infrastructure.ProvideSaveFileCommand(fileRepository, eventPublisher)
	return saveFileCommand
}

func InitializeDeleteFileCommand() *commands.DeleteFileCommand {
	fileRepository := infrastructure.ProvideFileRepository()
	deleteFileCommand := infrastructure.ProvideDeleteFileCommand(fileRepository)
	return deleteFileCommand
}

func InitializeGetFileQuery() *queries.GetFileQuery {
	fileRepository := infrastructure.ProvideFileRepository()
	getFileQuery := infrastructure.ProvideGetFileQuery(fileRepository)
	return getFileQuery
}
