// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"file-storage/API/routes"
	"file-storage/Application/commands"
	"file-storage/Application/handlers"
	"file-storage/Application/queries"
	"file-storage/Infrastructure/config"
	"file-storage/Infrastructure/db"
	"file-storage/Infrastructure/publisher"
	"file-storage/Infrastructure/queue"
	"file-storage/Infrastructure/repository"
)

// Injectors from wire.go:

func InitializeApplication() (*routes.Router, error) {
	configConfig := config.ProvideConfig()
	collection, err := db.ProvideMongoCollection(configConfig)
	if err != nil {
		return nil, err
	}
	fileRepository := repository.ProvideFileRepository(collection)
	jetStreamContext, err := queue.ProvideJetStreamContext(configConfig)
	if err != nil {
		return nil, err
	}
	eventPublisher, err := publisher.ProvideEventPublisher(jetStreamContext)
	if err != nil {
		return nil, err
	}
	saveFileCommand := commands.ProvideSaveFileCommand(fileRepository, eventPublisher)
	saveFileHandler := handlers.NewSaveFileHandler(saveFileCommand)
	getFileQuery := queries.ProvideGetFileQuery(fileRepository)
	getFileHandler := handlers.NewGetFileHandler(getFileQuery)
	deleteFileCommand := commands.ProvideDeleteFileCommand(fileRepository)
	deleteFileHandler := handlers.NewDeleteFileHandler(deleteFileCommand)
	v := handlers.ProvideHandlers(saveFileHandler, getFileHandler, deleteFileHandler)
	handlersHandlers := handlers.NewHandlers(v)
	router := routes.NewRouter(handlersHandlers)
	return router, nil
}
